### ISSUE TITLE
加密后部分CSS样式出现问题，JS失效，需要刷新才能恢复正常。

### ISSUE THREAD

**Issue by nanbowanya** [yiyungent/hexo-encrypt-token#3]
开发者你好，我再使用icarus主题时，添加hexo-encrypt-token插件后遇到两个问题
1、加密文章解密后部分文章样式会错误以及目录定位功能失效，需刷新。
2、对于文档介绍中的加密文章toc目录,实现隐藏toc为ejs方式，请问jsx格式文件该如何修改。（准确说想知道icarus在使用加密插件时该如何隐藏toc）

**Comment by yiyungent** [comment]
你在用这个包？？？我都没写文档的，本来自用的，我看其他人都没兴趣加密，还喷我。

1. 样式错误，可能这个样式是 js 动态设置的，而它可能在解密文章内容之前发生了，导致找不到元素从而失效。你可能需要在解密后再调用设置样式的函数。

2. 加密后，目录功能是很容易出问题，原本一般文章数据是保存在 `post.content`, 可是由于加密后，这个数据就变成加密数据了，需要使用 `post.origin`

https://github.com/yiyungent/hexo-encrypt-token/blob/2f27f428716d2d345e4cd1102f4eb98364e6f490/index.js#L68

我也没啥好办法，只有你自己看下主题源码，对照着修改，我倒是针对 NexT 主题弄好了

**Comment by nanbowanya** [comment]
好吧，感谢答复。我再看看
